version: '3'
services:
    app:
        container_name: app-dev
        depends_on:
            - redis
            - postgres
        build:
            dockerfile: ./.docker/node.js.dev.Dockerfile
            context: .
        restart: always
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '5000:5000'
            - '9229:9229'
        networks:
            - app-network

    postgres:
        container_name: postgres-dev
        image: postgres:13.2
        environment:
            PG_DATA: /var/lib/postgresql/data
            POSTGRES_USER: diamond_sword
            POSTGRES_PASSWORD: too_shiny
            POSTGRES_DB: sword_db
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - app-network

    redis:
        container_name: redis-dev
        image: redis:6.2
        restart: always
        ports:
            - '6379:6379'
        networks:
            - app-network

networks:
    app-network:

volumes:
    database-data:
